### ISSUE TITLE
Samsung Galaxy S8 and S9 with Android Oreo fail to connect to IsoDep NFC tag without NDEF content

### ISSUE THREAD

**Issue by otbinary** [NXPNFCLinux/nxpnfc_android_oreo#1]
Under Android Oreo Galaxy S8 and S9 smartphones won't connect any more to our IsoDep tags. The tags do not contain an NDEF message (on purpose), which seems to cause the connection issue. Communication with the tags worked flawlessly on the S8 under Android Nougat.

Do you happen to know if Samsung uses the NXPNFCLinux drivers in their Android builds for the S8 and S9 or what other drivers are used?

Is this the right place to report the issue?

Any hint to report and resolve the problem is appreciated.

Logcat extract:
```
04-20 11:14:04.610 4433-4433/? E/NfcLogManager: insertLog::feature=NF04
04-20 11:14:04.613 4433-4433/? D/NativeNfcTag: Connect to a tech with a different handle
04-20 11:14:04.632 4433-25088/? E/SecNfcNfa: rw_t4t_validate_cc_file (): max_file_size (0) is reserved
04-20 11:14:04.632 4433-25088/? E/SecNfcJni: nativeNfcTag_doCheckNdefResult: Check Ndef Failed (flags =0x8) , (status =0xE7)
04-20 11:14:04.632 4433-25088/? E/SecNfcJni: nativeNfcTag_doCheckNdefResult: no NDEF content on the tag (status =0xE7)
04-20 11:14:04.632 4433-4433/? D/NativeNfcTag: Check NDEF Failed - status = 3
04-20 11:14:05.660 4433-25088/? E/SecNfcJni: NfcTag::connectionEventHandler: NDEF detection timed out
04-20 11:14:05.662 4433-25088/? E/SecNfcJni: nativeNfcTag_doCheckNdefResult: unknown status=0xB2
04-20 11:14:05.675 4433-4433/? D/NativeNfcTag: Check NDEF Failed - status = 178
04-20 11:14:05.676 4433-4433/? E/SecNfcJni: nativeNfcTag_doReconnect: tag already deactivated
04-20 11:14:05.676 4433-4433/? E/SecNfcJni: nativeNfcTag_doDisconnect: tag already deactivated
04-20 11:14:05.676 4433-4433/? D/NfcService: [BIG DATA] TAG SUCCESS!!! PROTOCOL= 8
04-20 11:14:05.676 4433-4433/? E/NfcService: makeAndSendLog - start
04-20 11:14:05.677 4433-4433/? I/chatty: uid=1027(nfc) com.android.nfc identical 4 lines
04-20 11:14:05.677 4433-4433/? E/NfcLogManager: insertLog::feature=TAGF
04-20 11:14:05.684 4433-4433/? E/NfcService: makeAndSendLog - finish
04-20 11:14:05.684 4433-4433/? E/NfcService: TAG ERROR= 3, PROTOCOL= 8
04-20 11:14:05.686 4433-4433/? E/NfcService: makeAndSendLog - start
04-20 11:14:05.686 4433-4433/? I/chatty: uid=1027(nfc) com.android.nfc identical 4 lines
04-20 11:14:05.686 4433-4433/? E/NfcLogManager: insertLog::feature=TAGF
04-20 11:14:05.689 4433-4433/? E/NfcService: makeAndSendLog - finish
04-20 11:14:06.766 4433-4433/? E/NfcLogManager: insertLog::feature=NF04
04-20 11:14:06.774 4433-4433/? D/NativeNfcTag: Connect to a tech with a different handle
04-20 11:14:06.799 4433-25088/? E/SecNfcNfa: rw_t4t_validate_cc_file (): max_file_size (0) is reserved
04-20 11:14:06.799 4433-25088/? E/SecNfcJni: nativeNfcTag_doCheckNdefResult: Check Ndef Failed (flags =0x8) , (status =0xE7)
04-20 11:14:06.799 4433-25088/? E/SecNfcJni: nativeNfcTag_doCheckNdefResult: no NDEF content on the tag (status =0xE7)
04-20 11:14:06.799 4433-4433/? D/NativeNfcTag: Check NDEF Failed - status = 3
04-20 11:14:07.837 4433-25088/? E/SecNfcJni: NfcTag::connectionEventHandler: NDEF detection timed out
04-20 11:14:07.838 4433-25088/? I/NfcService: Skip makeTagRWLog:: System.currentTimeMillis()/1000 - tagLastDetectTime = 2 sec
04-20 11:14:07.839 4433-25088/? E/SecNfcJni: nativeNfcTag_doCheckNdefResult: unknown status=0xB2
04-20 11:14:07.849 4433-4433/? D/NativeNfcTag: Check NDEF Failed - status = 178
04-20 11:14:07.849 4433-4433/? E/SecNfcJni: nativeNfcTag_doReconnect: tag already deactivated
04-20 11:14:07.849 4433-4433/? E/SecNfcJni: nativeNfcTag_doDisconnect: tag already deactivated
```

**Comment by jgeslin** [comment]
Hi,

Indeed this is not the right place to address this issue. Samsung Galaxy S8 and S9 phones are definitely not built from NXPNCILinux driver for Android Oreo because it is targeting NXP PN7150 and those phones certainly don't integrate this NFC Controller.

I didn't have yet the opportunity to check this behavior by myself but I would be really surprise of this limitation. Did you check that your card is able to be read with generic application like https://play.google.com/store/apps/details?id=com.nxp.taginfolite ?

Regards,
Jeremy.

**Comment by otbinary** [comment]
Hello Jeremy

Thanks a lot for getting back to me! 

Yes, the NXP TagInfo app and other generic tag reader apps cannot read the tag either. Again, reading these tags with these apps works fine on Galaxy S8 phones with Android 7, but not any more with Android 8, because the OS seems unhappy with the missing NDEF content.

If we put an NDEF message on the tags, Android tag detection works as expected and we can successfully communicate with them using low-level transceive operations. Unfortunately, we cannot do that for the tens of thousands of devices deployed around the globe that are equipped with the tags. (The devices are air volume controllers in heating and cooling systems and provide an NFC interface for configuration and maintenance).

According to iFixit Teardowns, the S8 uses a NXP 80T71 NFC controller, and the S9 a NXP PN80T. I did not find theses controllers on the NXP site. Do you happen to know what chips these IDs may refer to? Do you happen to know if the Android drivers for these chips are partially based on your NXPNCILinux drivers and how I may contact an engineer involved in their development?

I've also filed an Android bug report (https://issuetracker.google.com/issues/80454359) for this issue. I am not very hopeful that it will be further analysed by Google because the issue only occurs on Samsung phones.

Kind regards,
Oliver
